### ISSUE TITLE
Release Docker image

### ISSUE THREAD

**Issue by ghostbear** [alessandrojean/tankobon#43]
### Describe your suggested feature

In PR #32 (related #27) a Dockerfile was added, allowing a Docker image to be created.

In a GitHub Action workflow, there should be steps to create a Docker image on a release tag and release it to either GitHub Packages or Docker Hub. PR #32 did have instructions on how to add this to the workflow. But the steps for the workflow are covered on this page: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

### Other details

This released image can then be used in a `docker-compose.yml` file
```yaml
version: '3.9'
services:
  tankobon:
    image: ghcr.io/alessandrojean/tankobon:latest
    ports:
      - "10101:8080"
    volumes:
      - /path/to/user_home/.tankobon:/root/.tankobon
```
Ports:
`10101` is the port that can be accessed outside of the container.
`8080` is the port for the server inside the container.
Volumes:
`/path/to/user_home/.tankobon` would be the path on the user machine.
`/root/.tankobon` path inside the container.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I filled out all of the requested information in this form.
