### ISSUE TITLE
Create new related entities directly from the book creation/edition form

### ISSUE THREAD

**Issue by phcreery** [alessandrojean/tankobon#49]
### Steps to reproduce

Using [5abb8b1](https://github.com/alessandrojean/tankobon/commit/5abb8b1)

Create a docker-compose.yml file.
```
version: '3.9'
services:
  tankobon:
    # To use the GitHub Packages image, use the line below instead.
    # image: ghcr.io/alessandrojean/tankobon:nightly
    image: alessandrojean/tankobon:nightly
    ports:
      # Tankobon will be available at port 25565.
      - '25565:8080'
    volumes:
      # The app files will be available outside the container.
      - /path/to/user_home/.tankobon:/root/.tankobon
```

Start a Docker container in detached mode.
```
$ docker-compose up -d
```
Open http://localhost:25565/ on a browser and proceed with the claim setup to create the first administrator user.

Try to create a book and I get this error while trying to create a book.
The contributor's tab is empty.

![image](https://github.com/user-attachments/assets/a8ab5926-9778-4802-addb-6c5a397a88ff)

### Expected behavior

Book gets created

### Actual behavior

Error message without any info to resolve

### Tankobon version

https://github.com/alessandrojean/tankobon/commit/5abb8b1

### Operating system

Debian 12, Docker

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I filled out all of the requested information in this form.
